server:
  port: 8081
  tomcat:
    max-swallow-size: -1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Atividades?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: M@ri@s10
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
jwt:
  secret: "1rsvQvjMQqo0aFz8LIi99NNjCTxbkpSjaPdjWkjtThs="
  expiration-ms: 86400000